import { HomeImageProps, PictureProps } from "../model/models";

export const pictureArray: PictureProps[] = [
  {
    id: 1,
    name: "1.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Зарождение”",
    titleEn: "The series “Digital Colonization Program” “Origin”",
    description: "",
    descriptionEn: "",
  },
  {
    id: 2,
    name: "2.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Социум”",
    titleEn: "Series “Digital Colonization Program” “Society”",
    description: "",
    descriptionEn: "",
  },
  {
    id: 3,
    name: "3.Eve1.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Сотворение Евы#2”",
    titleEn: "“Liquid Mirror” series“ The Creation of Eve#2”",
    description: "2022г., бумага, акварель, 38х56см",
    descriptionEn: "2022, watercolor on paper, 38x56cm",
  },
  {
    id: 4,
    name: "3.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Выход из системы”",
    titleEn: "Series “Digital Colonization Program” “Log out of the system”",
    description: "",
    descriptionEn: "",
  },
  {
    id: 5,
    name: "4.Insight.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Инсайт”",
    titleEn: "“Liquid Mirror” series “Insight”",
    description: "2021г., бумага, акварель, 38х56см",
    descriptionEn: "2021, watercolor on paper, 38x56cm",
  },
  {
    id: 6,
    name: "6.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Downloaded”",
    titleEn: "Series “Digital Colonization Program” “Downloaded”",
    description: "",
    descriptionEn: "",
  },
  {
    id: 7,
    name: "7.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Матричная ДНК”",
    titleEn: "Series “Digital Colonization Program” “Matrix DNA”",
    description: "",
    descriptionEn: "",
  },
  {
    id: 8,
    name: "Agora.jpg",
    type: "watercolour",
    title: "Серия “Город как живой организм” “Агора. Неиссякаемый источник”",
    titleEn:
      "Series “City as a Living Organism” ”Agora. An inexhaustible source”",
    description: "2022г., бумага, акварель, 38х56см",
    descriptionEn: "2022, paper, watercolor, 38x56cm",
  },
  {
    id: 9,
    name: "IMG_2516.jpg",
    type: "watercolour",
    title: "Серия “Код жизни” “Ультрамарин”",
    titleEn: "Series “Code of Life” “Ultramarine”",
    description: "2021г., бумага, акварель, 38х38см",
    descriptionEn: "2021, watercolor on paper, 38x38cm",
  },
  {
    id: 10,
    name: "IMG_2517.jpg",
    type: "watercolour",
    title: "Серия “Код жизни” “Индивидуальные черты”",
    titleEn: "Series “Code of Life” “Individual traits”",
    description: "2021г., бумага, акварель 38х38см",
    descriptionEn: "2021, watercolor on paper 38x38cm",
  },
  {
    id: 11,
    name: "IMG_4504.jpg",
    type: "watercolour",
    title: "Серия “Культурный код”, 1 часть",
    titleEn: "Series “Cultural code”, part 1",
    description: "2022г., бумага, акварель, 38х38см",
    descriptionEn: "2022, paper, watercolor, 38x38 cm",
  },
  {
    id: 12,
    name: "IMG_4669.jpg",
    type: "watercolour",
    title: "Серия “Культурный код”, 2 часть",
    titleEn: "Series “Cultural Code”, part 2",
    description: "2022г., бумага, акварель, 38х38см",
    descriptionEn: "2022, paper, watercolor, 38x38 cm",
  },
  {
    id: 13,
    name: "Keeper_of_Treasures.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” Хранитель сокровищ”",
    titleEn: "“Liquid Mirror” series ”Treasure keeper”",
    description: "2022г., бумага, акварель, 38х56см",
    descriptionEn: "2022, watercolor on paper, 38x56cm",
  },
  {
    id: 14,
    name: "m9.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Металюди”",
    titleEn: "Series “Digital Colonization Program” “Metahumans”",
    description: "",
    descriptionEn: "",
  },
  {
    id: 15,
    name: "Nadia_Khovaeva_Here_she_comes_again.jpg",
    type: "watercolour",
    title: "“Here she comes again”",
    titleEn: "Series “City as a Living Organism” “Here she comes again”",
    description: "2021, бумага, акварель, 38х56см",
    descriptionEn: "2021, watercolor on paper, 38x56cm",
  },
  {
    id: 16,
    name: "Nadia_Khovaeva_Roll_Call_1.jpg",
    type: "watercolour",
    title: "Серия “Код жизни” “Перекличка”",
    titleEn: "Series “Code of Life” “Roll call”",
    description: "2021г., бумага, акварель, 38х38см Оммаж Броису Лурье.",
    descriptionEn: "2021, watercolor on paper, 38x38cm Homage to Brois Lurie.",
  },
  {
    id: 17,
    name: "The_Birth_of_Eve.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” Серия “Жидкое зеркало” “Сотворение Евы”",
    titleEn: "“Liquid Mirror” series “The Creation of Eve”",
    description: "2022г., бумага, акварель, 38х56см",
    descriptionEn: "2022, watercolor on paper, 38x56cm",
  },
  {
    id: 18,
    name: "Twinkle.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Мерцание”",
    titleEn: "“Liquid Mirror” series “Twinkle”",
    description: "2022г., бумага, акварель, 56х38см",
    descriptionEn: "2022, watercolor on paper, 56x38cm",
  },
  {
    id: 19,
    name: "ДНК.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “ДНК волоса неизвестного”",
    titleEn: "“Liquid Mirror” series “DNA of an unknown hair”",
    description: "2021г., бумага, акварель, 38х56см",
    descriptionEn: "2021, watercolor on paper, 38x56cm",
  },
  {
    id: 20,
    name: "Зеркало.jpg",
    type: "watercolour",
    title: "Серия “Трансформация” “Трансформация времени”",
    titleEn: "Series “Transformation” “Transformation of time”",
    description: "2022г., бумага, акварель 56х38см",
    descriptionEn: "2022, watercolor on paper 56x38cm",
  },
  {
    id: 21,
    name: "Идеальный_шторм.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Идеальный шторм”",
    titleEn: "“Liquid Mirror” series “The Perfect Storm”",
    description: "2021г., бумага, акварель, 38х28см",
    descriptionEn: "2021, watercolor on paper, 38x28cm",
  },
  {
    id: 22,
    name: "Импульсы2.jpg",
    type: "watercolour",
    title: "Серия “Город как живой организм” “Импульсы”",
    titleEn: "Series “City as a Living Organism” “Impulses”",
    description: "2022г., бумага, акварель, 56х38см",
    descriptionEn: "2022, watercolor on paper, 56x38cm",
  },
  {
    id: 23,
    name: "Клонирование.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Клонирование”",
    titleEn: "Series “Digital Colonization Program” “Cloning”",
    description: "",
    descriptionEn: "",
  },
  {
    id: 24,
    name: "Культурный_код2.jpg",
    type: "watercolour",
    title: "Серия “Культурный код”, 3 часть",
    titleEn: "Series “Cultural Code”, part 3",
    description: "2022г., бумага, акварель, 38х38см",
    descriptionEn: "2022, paper, watercolor, 38x38 cm",
  },
  {
    id: 25,
    name: "Пересборка_Ховаева_Н.В..jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Пересборка”",
    titleEn: "“Liquid Mirror” series “Reassembly”",
    description: "2022г., бумага, акварель триптих 56х38см каждая часть",
    descriptionEn: "2022, watercolor on paper triptych 56x38cm each piece",
  },
  {
    id: 26,
    name: "Перспектива.jpg",
    type: "watercolour",
    title: "Серия “Трансформация” Трансформация пространства”",
    titleEn: "Series “Transformation” Transformation of space”",
    description: "2022г., бумага, акварель, 56х38см",
    descriptionEn: "2022, watercolor on paper, 56x38cm",
  },
  {
    id: 27,
    name: "Покойпокой.jpg",
    type: "watercolour",
    title: "Серия “Трансформация” “Покой покой”",
    titleEn: "Series “Transformation” “Peace of peace”",
    description: "2022г., бумага, акварель, 56х38см",
    descriptionEn: "2022, watercolor on paper, 56x38cm",
  },
  {
    id: 28,
    name: "Трансформация.jpg",
    type: "watercolour",
    title: "Серия “Трансформация” “Трансформация времени и пространства”",
    titleEn: "Series “Transformation” “Transformation of time and space”",
    description: "2022г., бумага, акварель, 56х76см",
    descriptionEn: "2022, watercolor on paper, 56x76cm",
  },
  {
    id: 29,
    name: "Фрактал.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Фрактал”",
    titleEn: "Series “Digital Colonization Program” “Fractal”",
    description: "",
    descriptionEn: "",
  },
  {
    id: 30,
    name: "Ховаева_Надежда_Ритмы города.Бумага-акварель.56х38.2021г..jpg",
    type: "watercolour",
    title: "Серия “Город как живой организм” “Ритмы города”",
    titleEn: "Series “City as a Living Organism” “Rhythms of the city”",
    description: "2021г., бумага, акварель, 56х38см",
    descriptionEn: "2021, watercolor on paper, 56x38cm",
  },
  {
    id: 31,
    name: "ХоваеваНадежда.Алхимия.56х38см.Бумага-акварель.50000руб.jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Алхимия”",
    titleEn: "Series “Transurfing unreality” “Alchemy”",
    description: "2022, бумага, акварель, 56х38см",
    descriptionEn: "2022, paper, watercolor, 56x38 cm",
  },
  {
    id: 32,
    name: "ХоваеваНадежда.Антигравитация.56х38см.Бумага-акварель.50000руб..jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Антигравитация”",
    titleEn: "Series “Transurfing unreality” “Antigravity”",
    description: "2022, бумага, акварель, 56х38см",
    descriptionEn: "2022, paper, watercolor, 56x38 cm",
  },
  {
    id: 33,
    name: "ХоваеваНадежда.Новыймонуменя.Бумага-акварель.56х38.2021г..jpg",
    type: "watercolour",
    title: "Серия “Город как живой организм” “Новый монумент”",
    titleEn: "Series “City as a Living Organism” “New Monument”",
    description: "2021г., бумага, акварель, 56х38см",
    descriptionEn: "2021, watercolor on paper, 56x38cm",
  },
  {
    id: 34,
    name: "ХоваеваНадежда.Сверхновая.jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Сверхновая”",
    titleEn: "The series “Transurfing unreality” “Supernova”",
    description: "2022, бумага, акварель, 56х38см",
    descriptionEn: "2022, paper, watercolor, 56x38 cm",
  },
  {
    id: 35,
    name: "ХоваеваНадежда.Сердцеангела.76х56см.Бумага-акварель.100000руб..jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Сердце ангела”",
    titleEn: "The series “Transurfing unreality” “Angel's Heart”",
    description: "2022, бумага, акварель, 76х56см",
    descriptionEn: "2022, paper, watercolor, 76x56 cm",
  },
  {
    id: 36,
    name: "ХоваеваНадежда.Феникс.56х38см.Бумага-акварель.50000руб.jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Феникс”",
    titleEn: "Series “Transurfing unreality” “Phoenix”",
    description: "2022, бумага, акварель, 56х38см",
    descriptionEn: "2022, paper, watercolor, 56x38 cm",
  },
  {
    id: 37,
    name: "я1.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Услышь”",
    titleEn: "“Liquid Mirror” series “Hear”",
    description: "2022г., бумага, акварель, 56х38см",
    descriptionEn: "2022, watercolor on paper, 56x38cm",
  },
  {
    id: 38,
    name: "Инсайт.jpg",
    type: "acrylic",
    title: "“Инсайт”",
    titleEn: "“Insight”",
    description: "2023, холст, акрил, 80х60см",
    descriptionEn: "2023, acrylic on canvas, 80x60 cm",
  },
  {
    id: 39,
    name: "НадеждаХоваева,Следуйзабелойтенью,акрилнахолсте,70х50,тираж1,2023,100000.jpg",
    type: "acrylic",
    title: "“Следуй за белой тенью”",
    titleEn: "“Follow the white shadow”",
    description: "2023г., холст, акврил, 70х50 см",
    descriptionEn: "2023, acrylic on canvas, 70x50 cm",
  },
  {
    id: 40,
    name: "Невесомостьабсолютногосчастья.jpg",
    type: "acrylic",
    title: "“Невесомость абсолютного счастья”",
    titleEn: "“The weightlessness of absolute happiness”",
    description: "2022, шелк, акрил, 140х200см",
    descriptionEn: "2022, silk, acrylic, 140x200 cm",
  },
  {
    id: 41,
    name: "IMG_4962.JPG",
    type: "phygital",
    title: "“Новый монумент”",
    titleEn: "“New Monument”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 42,
    name: "IMG_4963.JPG",
    type: "phygital",
    title: "“ДНК.Новый монумент”",
    titleEn: "“DNA.New Monument”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 43,
    name: "Zoloto3.jpg",
    type: "phygital",
    title: "“Золото пустыни”",
    titleEn: "“Desert Gold”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 44,
    name: "Бабочка1.jpg",
    type: "phygital",
    title: "“Золотая пыль вечности”",
    titleEn: "“The golden dust of eternity”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 45,
    name: "бак1.jpg",
    type: "phygital",
    title: "“Страна О”",
    titleEn: "“Country O”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 46,
    name: "витрувий2.jpg",
    type: "phygital",
    title: "“Река забвения”",
    titleEn: "“The River of Oblivion”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 47,
    name: "инсайт1.jpg",
    type: "phygital",
    title: "“Инсайт#3”",
    titleEn: "“Insight#3”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 48,
    name: "лебедь1.jpg",
    type: "phygital",
    title: "“Алхимия”",
    titleEn: "“Alchemy”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 49,
    name: "п1.jpg",
    type: "phygital",
    title: "“Ева#4”",
    titleEn: "“Eve#4”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 50,
    name: "Паруса1.jpg",
    type: "phygital",
    title: "“NV”",
    titleEn: "“NV”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 51,
    name: "пер5.jpg",
    type: "phygital",
    title: "“Ева#5”",
    titleEn: "“Eve#5”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 52,
    name: "ПокооителигорвершинХ2.jpg",
    type: "phygital",
    title: "“Покорители горных вершин”",
    titleEn: "“Conquerors of mountain peaks”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 53,
    name: "Садкамней.jpg",
    type: "phygital",
    title: "“Смотри внутрь”",
    titleEn: "“Look inside”",
    description: "2023",
    descriptionEn: "2023",
  },
  {
    id: 54,
    name: "Трансформация.jpg",
    type: "phygital",
    title: "“Трансформация времени и пространства”",
    titleEn: "“Transformation of time and space”",
    description: "2023",
    descriptionEn: "2023",
  },
];

export const homeImages: HomeImageProps[] = [
  {
    id: 1,
    name: "watercolour/Клонирование.jpg",
  },
  {
    id: 2,
    name: "watercolour/Agora.jpg",
  },
  {
    id: 3,
    name: "watercolour/ХоваеваНадежда.Сверхновая.jpg",
  },
  {
    id: 4,
    name: "phygital/витрувий2.jpg",
  },
  {
    id: 5,
    name: "phygital/Zoloto3.jpg",
  },
  {
    id: 6,
    name: "watercolour/IMG_4669.jpg",
  },
  {
    id: 7,
    name: "acrylic/Инсайт.jpg",
  },
  {
    id: 8,
    name: "watercolour/Покойпокой.jpg",
  },
];

export const pictureDescriptions = [
  {
    title: "Акварель",
    titleEn: "Watercolour",
    description:
      "Акварельные картины — это тип художественных работ, созданных с использованием акварели, представляющей собой краски, полученные путем смешивания воды и пигмента.",
    descriptionEn:
      "Watercolor pictures are a type of artwork that is created using watercolors, which are paints made by combining water and pigment.",
    type: "watercolour",
  },
  {
    title: "Акрил",
    titleEn: "Acrylic",
    description:
      "Акриловые картины обычно относятся к искусству, созданному с использованием акриловой краски. Акриловая краска — это быстросохнущая краска, которая растворяется в воде во влажном состоянии, но становится водостойкой при высыхании.",
    descriptionEn:
      "Acrylic pictures typically refer to art created using acrylic paint. Acrylic paint is a fast-drying paint that is water-soluble when wet but becomes water-resistant when it dries.",
    type: "acrylic",
  },
  {
    title: "Phygital",
    titleEn: "Phygital",
    description:
      "Все цифровые работы состоят из множества акварелей, написанных Надеждой, объединенных и преобразованных в цифровой формат, тем самым усиливая эффект многомерности, бесконечности и трансформации.",
    descriptionEn:
      "All digital works consist of many watercolors painted by Nadezhda, combined and converted into a digital format, thereby enhancing the effect of multidimensionality, infinity and transformation.",
    type: "phygital",
  },
];
