import { HomeImageProps, PictureProps } from "../model/models";

export const pictureArray: PictureProps[] = [
  {
    id: 3,
    name: "3.Eve1.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Сотворение Евы#2”",
    titleEn: "“Liquid Mirror” series“ The Creation of Eve#2”",
    subtitle: "2022г., бумага, акварель, 38х56см",
    subtitleEn: "2022, watercolor on paper, 38x56cm",
    description:
      "Человечество всегда пыталось осознать себя и свое место в этом мире. С развитием науки и технологий открываются новые возможности. И вот мы уже знаем, что произошли от митохондриальной Евы, названной в честь библейской, а генетики создают новую Еву - клона-младенца. Мы живем в мире, где можно клонировать животных, флиртовать с виртуальными девушками и играть с роботами. А однажды, вернувшись домой, вы можете обнаружить копию самого себя - который занял ваше место. Стирается грань между реальностью и фантастикой.",
    descriptionEn:
      "Humanity has always tried to realize itself and its place in this world. With the development of science and technology, new opportunities are opening up. And now we already know that we have descended from mitochondrial Eve, named after the biblical one, and geneticists are creating a new Eve - a baby clone. We live in a world where you can clone animals, flirt with virtual girls and play with robots. And one day, when you return home, you may find a copy of yourself - who has taken your place. The line between reality and fiction is blurred.",
  },
  {
    id: 5,
    name: "4.Insight.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Инсайт”",
    titleEn: "“Liquid Mirror” series “Insight”",
    subtitle: "2021г., бумага, акварель, 38х56см",
    subtitleEn: "2021, watercolor on paper, 38x56cm",
    description:
      "Во многих традициях зеркало является символом души человека, ее вместилищем. Заглянуть сквозь жидкое зеркало - познать себя, обрести высшую силу.",
    descriptionEn:
      "In many traditions, the mirror is a symbol of the human soul, its receptacle. To look through a liquid mirror is to know yourself, to gain a higher power.",
  },
  {
    id: 13,
    name: "Keeper_of_Treasures.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” Хранитель сокровищ”",
    titleEn: "“Liquid Mirror” series ”Treasure keeper”",
    subtitle: "2022г., бумага, акварель, 38х56см",
    subtitleEn: "2022, watercolor on paper, 38x56cm",
    description:
      "Сильный и стремительный, уверенный и могущественный, мудрый и просвященный, охраняет путь к спасению, Древу Жизни. Только избранных, решившихся пройти этот путь грифон наделяет своими королевскими качествами.",
    descriptionEn:
      "Strong and impetuous, confident and powerful, wise and enlightened, guards the path to salvation, the Tree of Life. Only the chosen ones, who decided to go this way, are endowed by the griffin with their royal qualities.",
  },
  {
    id: 17,
    name: "The_Birth_of_Eve.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Сотворение Евы”",
    titleEn: "“Liquid Mirror” series “The Creation of Eve”",
    subtitle: "2022г., бумага, акварель, 38х56см",
    subtitleEn: "2022, watercolor on paper, 38x56cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 18,
    name: "Twinkle.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Мерцание”",
    titleEn: "“Liquid Mirror” series “Twinkle”",
    subtitle: "2022г., бумага, акварель, 56х38см",
    subtitleEn: "2022, watercolor on paper, 56x38cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 19,
    name: "ДНК.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “ДНК волоса неизвестного”",
    titleEn: "“Liquid Mirror” series “DNA of an unknown hair”",
    subtitle: "2021г., бумага, акварель, 38х56см",
    subtitleEn: "2021, watercolor on paper, 38x56cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 21,
    name: "Идеальный_шторм.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Идеальный шторм”",
    titleEn: "“Liquid Mirror” series “The Perfect Storm”",
    subtitle: "2021г., бумага, акварель, 38х28см",
    subtitleEn: "2021, watercolor on paper, 38x28cm",
    description:
      "Самая мощная стихия та, что внутри нас. Преодолеть ее - обрести невероятную силу.",
    descriptionEn:
      "The most powerful element is the one inside us. To overcome it is to gain incredible strength.",
  },
  {
    id: 25,
    name: "Пересборка_Ховаева_Н.В..jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Пересборка”",
    titleEn: "“Liquid Mirror” series “Reassembly”",
    subtitle: "2022г., бумага, акварель триптих 56х38см",
    subtitleEn: "2022, watercolor on paper triptych 56x38cm",
    description:
      "Быть искренним - открытым и уязвимым, и каждый раз пытаться пересобрать Вселенную из осколков миров, сохраняя хрупкую надежду.",
    descriptionEn:
      "Being sincere means being open and vulnerable, and every time trying to rebuild the universe from the fragments of worlds, preserving fragile hope.",
  },
  {
    id: 37,
    name: "я1.jpg",
    type: "watercolour",
    title: "Серия “Жидкое зеркало” “Услышь”",
    titleEn: "“Liquid Mirror” series “Hear”",
    subtitle: "2022г., бумага, акварель, 56х38см",
    subtitleEn: "2022, watercolor on paper, 56x38cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 9,
    name: "IMG_2516.jpg",
    type: "watercolour",
    title: "Серия “Код жизни” “Ультрамарин”",
    titleEn: "Series “Code of Life” “Ultramarine”",
    subtitle: "2021г., бумага, акварель, 38х38см",
    subtitleEn: "2021, watercolor on paper, 38x38cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 10,
    name: "IMG_2517.jpg",
    type: "watercolour",
    title: "Серия “Код жизни” “Индивидуальные черты”",
    titleEn: "Series “Code of Life” “Individual traits”",
    subtitle: "2021г., бумага, акварель 38х38см",
    subtitleEn: "2021, watercolor on paper 38x38cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 16,
    name: "Nadia_Khovaeva_Roll_Call_1.jpg",
    type: "watercolour",
    title: "Серия “Код жизни” “Перекличка”",
    titleEn: "Series “Code of Life” “Roll call”",
    subtitle: "2021г., бумага, акварель, 38х38см Оммаж Броису Лурье.",
    subtitleEn: "2021, watercolor on paper, 38x38cm Homage to Brois Lurie.",
    description: "",
    descriptionEn: "",
  },
  {
    id: 8,
    name: "Agora.jpg",
    type: "watercolour",
    title: "Серия “Город как живой организм” “Агора. Неиссякаемый источник”",
    titleEn:
      "Series “City as a Living Organism” ”Agora. An inexhaustible source”",
    subtitle: "2022г., бумага, акварель, 38х56см",
    subtitleEn: "2022, paper, watercolor, 38x56cm",
    description:
      "В Агоре (Измире) есть древние руины в виде арок, а под ними еще со времен Гомера протекает источник. В этих руинах я вижу древний амулет - глаз, означающий “Смотри внутрь”, вокруг которого сложено множество легенд о любви и верности. Каждый виток - кольцо времени, на протяжении веков женщина дарит жизнь, хранит очаг, жертвует собой ради любви, это и есть - неиссякаемый источник.",
    descriptionEn:
      "There are ancient ruins in the form of arches in the Agora (Izmir), and a spring has been flowing under them since the time of Homer. In these ruins I see an ancient amulet - the eye, meaning “Look inside”, around which many legends about love and loyalty are composed. Every turn is a ring of time, for centuries a woman gives life, keeps a hearth, sacrifices herself for love, this is an inexhaustible source.",
  },
  {
    id: 22,
    name: "Импульсы2.jpg",
    type: "watercolour",
    title: "Серия “Город как живой организм” “Импульсы”",
    titleEn: "Series “City as a Living Organism” “Impulses”",
    subtitle: "2022г., бумага, акварель, 56х38см",
    subtitleEn: "2022, watercolor on paper, 56x38cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 30,
    name: "Ховаева_Надежда_Ритмы города.Бумага-акварель.56х38.2021г..jpg",
    type: "watercolour",
    title: "Серия “Город как живой организм” “Ритмы города”",
    titleEn: "Series “City as a Living Organism” “Rhythms of the city”",
    subtitle: "2021г., бумага, акварель, 56х38см",
    subtitleEn: "2021, watercolor on paper, 56x38cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 33,
    name: "ХоваеваНадежда.Новыймонуменя.Бумага-акварель.56х38.2021г..jpg",
    type: "watercolour",
    title: "Серия “Город как живой организм” “Новый монумент”",
    titleEn: "Series “City as a Living Organism” “New Monument”",
    subtitle: "2021г., бумага, акварель, 56х38см",
    subtitleEn: "2021, watercolor on paper, 56x38cm",
    description:
      "В этой работе я хочу заострить внимание на том, как меняются повседневные реалии, как цифровой мир сливается с нашей жизнью. Будет ли новый монумент защитой и оберегом, подобно “Родине-мать”, призывающей объединиться ради спасения будущих поколений,  или наоборот? Я бы хотела, чтобы каждый ответил себе на этот вопрос и воздвиг этот образ в своем сознании.",
    descriptionEn:
      "In this work, I want to focus on how everyday realities are changing, how the digital world merges with our lives. Will the new monument be a protection and a talisman, like the “Motherland”, calling to unite for the sake of saving future generations, or vice versa? I would like everyone to answer this question for themselves and erect this image in their minds.",
  },
  {
    id: 20,
    name: "Зеркало.jpg",
    type: "watercolour",
    title: "Серия “Трансформация” “Трансформация времени”",
    titleEn: "Series “Transformation” “Transformation of time”",
    subtitle: "2022г., бумага, акварель 56х38см",
    subtitleEn: "2022, watercolor on paper 56x38cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 26,
    name: "Перспектива.jpg",
    type: "watercolour",
    title: "Серия “Трансформация” Трансформация пространства”",
    titleEn: "Series “Transformation” Transformation of space”",
    subtitle: "2022г., бумага, акварель, 56х38см",
    subtitleEn: "2022, watercolor on paper, 56x38cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 27,
    name: "Покойпокой.jpg",
    type: "watercolour",
    title: "Серия “Трансформация” “Покой покой”",
    titleEn: "Series “Transformation” “Peace of peace”",
    subtitle: "2022г., бумага, акварель, 56х38см",
    subtitleEn: "2022, watercolor on paper, 56x38cm",
    description:
      "“Вечный покой был когда-то нарушен и мир рассыпался на различия и теперь беснуется и идет вновь к миру безразличному. “Казимир Малевич”",
    descriptionEn:
      "“Eternal peace was once broken and the world crumbled into differences and now it is raging and going back to the indifferent world. “Kazimir Malevich”",
  },
  {
    id: 28,
    name: "Трансформация.jpg",
    type: "watercolour",
    title: "Серия “Трансформация” “Трансформация времени и пространства”",
    titleEn: "Series “Transformation” “Transformation of time and space”",
    subtitle: "2022г., бумага, акварель, 56х76см",
    subtitleEn: "2022, watercolor on paper, 56x76cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 31,
    name: "ХоваеваНадежда.Алхимия.56х38см.Бумага-акварель.50000руб.jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Алхимия”",
    titleEn: "Series “Transurfing unreality” “Alchemy”",
    subtitle: "2022, бумага, акварель, 56х38см",
    subtitleEn: "2022, paper, watercolor, 56x38 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 32,
    name: "ХоваеваНадежда.Антигравитация.56х38см.Бумага-акварель.50000руб..jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Антигравитация”",
    titleEn: "Series “Transurfing unreality” “Antigravity”",
    subtitle: "2022, бумага, акварель, 56х38см",
    subtitleEn: "2022, paper, watercolor, 56x38 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 34,
    name: "ХоваеваНадежда.Сверхновая.jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Сверхновая”",
    titleEn: "The series “Transurfing unreality” “Supernova”",
    subtitle: "2022, бумага, акварель, 56х38см",
    subtitleEn: "2022, paper, watercolor, 56x38 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 35,
    name: "ХоваеваНадежда.Сердцеангела.76х56см.Бумага-акварель.100000руб..jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Сердце ангела”",
    titleEn: "The series “Transurfing unreality” “Angel's Heart”",
    subtitle: "2022, бумага, акварель, 76х56см",
    subtitleEn: "2022, paper, watercolor, 76x56 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 36,
    name: "ХоваеваНадежда.Феникс.56х38см.Бумага-акварель.50000руб.jpg",
    type: "watercolour",
    title: "Серия “Трансерфинг нереальности” “Феникс”",
    titleEn: "Series “Transurfing unreality” “Phoenix”",
    subtitle: "2022, бумага, акварель, 56х38см",
    subtitleEn: "2022, paper, watercolor, 56x38 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 11,
    name: "IMG_4504.jpg",
    type: "watercolour",
    title: "Серия “Культурный код”, 1 часть",
    titleEn: "Series “Cultural code”, part 1",
    subtitle: "2022г., бумага, акварель, 38х38см",
    subtitleEn: "2022, paper, watercolor, 38x38 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 12,
    name: "IMG_4669.jpg",
    type: "watercolour",
    title: "Серия “Культурный код”, 2 часть",
    titleEn: "Series “Cultural Code”, part 2",
    subtitle: "2022г., бумага, акварель, 38х38см",
    subtitleEn: "2022, paper, watercolor, 38x38 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 24,
    name: "Культурный_код2.jpg",
    type: "watercolour",
    title: "Серия “Культурный код”, 3 часть",
    titleEn: "Series “Cultural Code”, part 3",
    subtitle: "2022г., бумага, акварель, 38х38см",
    subtitleEn: "2022, paper, watercolor, 38x38 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 1,
    name: "1.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Зарождение”",
    titleEn: "The series “Digital Colonization Program” “Origin”",
    subtitle: "",
    subtitleEn: "",
    description: "",
    descriptionEn: "",
  },
  {
    id: 2,
    name: "2.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Социум”",
    titleEn: "Series “Digital Colonization Program” “Society”",
    subtitle: "",
    subtitleEn: "",
    description: "",
    descriptionEn: "",
  },
  {
    id: 4,
    name: "3.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Выход из системы”",
    titleEn: "Series “Digital Colonization Program” “Log out of the system”",
    subtitle: "",
    subtitleEn: "",
    description: "",
    descriptionEn: "",
  },
  {
    id: 6,
    name: "6.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Downloaded”",
    titleEn: "Series “Digital Colonization Program” “Downloaded”",
    subtitle: "",
    subtitleEn: "",
    description: "",
    descriptionEn: "",
  },
  {
    id: 7,
    name: "7.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Матричная ДНК”",
    titleEn: "Series “Digital Colonization Program” “Matrix DNA”",
    subtitle: "",
    subtitleEn: "",
    description: "",
    descriptionEn: "",
  },
  {
    id: 14,
    name: "m9.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Металюди”",
    titleEn: "Series “Digital Colonization Program” “Metahumans”",
    subtitle: "",
    subtitleEn: "",
    description: "",
    descriptionEn: "",
  },
  {
    id: 23,
    name: "Клонирование.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Клонирование”",
    titleEn: "Series “Digital Colonization Program” “Cloning”",
    subtitle: "",
    subtitleEn: "",
    description: "",
    descriptionEn: "",
  },
  {
    id: 29,
    name: "Фрактал.jpg",
    type: "watercolour",
    title: "Серия “Программа цифровой колонизации” “Фрактал”",
    titleEn: "Series “Digital Colonization Program” “Fractal”",
    subtitle: "",
    subtitleEn: "",
    description: "",
    descriptionEn: "",
  },
  {
    id: 15,
    name: "Nadia_Khovaeva_Here_she_comes_again.jpg",
    type: "watercolour",
    title: "“Here she comes again”",
    titleEn: "Series “City as a Living Organism” “Here she comes again”",
    subtitle: "2021, бумага, акварель, 38х56см",
    subtitleEn: "2021, watercolor on paper, 38x56cm",
    description:
      "Душа - сознательная часть энергии любви, обладающей памятью. Частицы своей души человек может оставлять привязанными к месту, ситуации, людям.",
    descriptionEn:
      "The soul is a conscious part of the energy of love, which has memory. A person can leave the particles of his soul tied to a place, situation, people.",
  },
  {
    id: 38,
    name: "Инсайт.jpg",
    type: "acrylic",
    title: "“Инсайт”",
    titleEn: "“Insight”",
    subtitle: "2023, холст, акрил, 80х60см",
    subtitleEn: "2023, acrylic on canvas, 80x60 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 39,
    name: "НадеждаХоваева,Следуйзабелойтенью,акрилнахолсте,70х50,тираж1,2023,100000.jpg",
    type: "acrylic",
    title: "“Следуй за белой тенью”",
    titleEn: "“Follow the white shadow”",
    subtitle: "2023г., холст, акрил, 70х50 см",
    subtitleEn: "2023, acrylic on canvas, 70x50 cm",
    description:
      "По словам Юнга, Тень — скрытая, неосознаваемая часть нас самих, в которой хранится все спрятанное и бессознательное, то, что не признается и отрицается нами – страхи, боль, обиды, а вместе с этим и мощный потенциал – нереализованные способности. Принимая все грани своей личности, в Тени мы можем открыть новую, неизвестную часть себя.",
    descriptionEn:
      "According to Jung, the Shadow is a hidden, unconscious part of ourselves, in which everything hidden and unconscious is stored, what is not recognized and denied by us — fears, pain, resentment, and with it a powerful potential – unrealized abilities. Accepting all facets of our personality, in the Shadows we can discover a new, unknown part of ourselves.",
  },
  {
    id: 40,
    name: "Невесомостьабсолютногосчастья.jpg",
    type: "acrylic",
    title: "“Невесомость абсолютного счастья”",
    titleEn: "“The weightlessness of absolute happiness”",
    subtitle: "2022, шелк, акрил, 140х200см",
    subtitleEn: "2022, silk, acrylic, 140x200 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 55,
    name: "IMG_6310.jpg",
    type: "acrylic",
    title: "“Алхимия”",
    titleEn: "“Alchemy”",
    subtitle: "2023, холст, акрил, 80х60 см",
    subtitleEn: "2023, acrylic on canvas, 80x60 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 56,
    name: "Покорителигорныхвершин.jpg",
    type: "acrylic",
    title: "“Покорители горных вершин”",
    titleEn: "“Conquerors of mountain peaks”",
    subtitle: "2023, холст, акрил, 50х60 см",
    subtitleEn: "2023, acrylic on canvas, 50x60 cm",
    description: "",
    descriptionEn: "",
  },
  {
    id: 41,
    name: "IMG_4962.JPG",
    type: "phygital",
    title: "“Новый монумент”",
    titleEn: "“New Monument”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 42,
    name: "IMG_4963.JPG",
    type: "phygital",
    title: "“ДНК.Новый монумент”",
    titleEn: "“DNA.New Monument”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 43,
    name: "Zoloto3.jpg",
    type: "phygital",
    title: "“Золото пустыни”",
    titleEn: "“Desert Gold”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 44,
    name: "Бабочка1.jpg",
    type: "phygital",
    title: "“Золотая пыль вечности”",
    titleEn: "“The golden dust of eternity”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 45,
    name: "бак1.jpg",
    type: "phygital",
    title: "“Страна О”",
    titleEn: "“Country O”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 46,
    name: "витрувий2.jpg",
    type: "phygital",
    title: "“Река забвения”",
    titleEn: "“The River of Oblivion”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 47,
    name: "инсайт1.jpg",
    type: "phygital",
    title: "“Инсайт#3”",
    titleEn: "“Insight#3”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 48,
    name: "лебедь1.jpg",
    type: "phygital",
    title: "“Алхимия”",
    titleEn: "“Alchemy”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 49,
    name: "п1.jpg",
    type: "phygital",
    title: "“Ева#4”",
    titleEn: "“Eve#4”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 50,
    name: "Паруса1.jpg",
    type: "phygital",
    title: "“NV”",
    titleEn: "“NV”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 51,
    name: "пер5.jpg",
    type: "phygital",
    title: "“Ева#5”",
    titleEn: "“Eve#5”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 52,
    name: "ПокооителигорвершинХ2.jpg",
    type: "phygital",
    title: "“Покорители горных вершин”",
    titleEn: "“Conquerors of mountain peaks”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 53,
    name: "Садкамней.jpg",
    type: "phygital",
    title: "“Смотри внутрь”",
    titleEn: "“Look inside”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 54,
    name: "Трансформация.jpg",
    type: "phygital",
    title: "“Трансформация времени и пространства”",
    titleEn: "“Transformation of time and space”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 57,
    name: "Insight4.jpg",
    type: "phygital",
    title: "“Инсайт#4”",
    titleEn: "“Insight#4”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
  {
    id: 58,
    name: "Возрождение.jpg",
    type: "phygital",
    title: "“Восхождение”",
    titleEn: "“Climbing”",
    subtitle: "2023",
    subtitleEn: "2023",
    description: "",
    descriptionEn: "",
  },
];

export const homeImages: HomeImageProps[] = [
  {
    id: 1,
    name: "watercolour/Клонирование.jpg",
  },
  {
    id: 2,
    name: "watercolour/Agora.jpg",
  },
  {
    id: 3,
    name: "watercolour/ХоваеваНадежда.Сверхновая.jpg",
  },
  {
    id: 4,
    name: "phygital/витрувий2.jpg",
  },
  {
    id: 5,
    name: "phygital/Zoloto3.jpg",
  },
  {
    id: 6,
    name: "watercolour/IMG_4669.jpg",
  },
  {
    id: 7,
    name: "acrylic/Инсайт.jpg",
  },
  {
    id: 8,
    name: "watercolour/Покойпокой.jpg",
  },
];

export const pictureDescriptions = [
  {
    title: "Акварель",
    titleEn: "Watercolour",
    description:
      "Акварельные картины — это тип художественных работ, созданных с использованием акварели, представляющей собой краски, полученные путем смешивания воды и пигмента.",
    descriptionEn:
      "Watercolor pictures are a type of artwork that is created using watercolors, which are paints made by combining water and pigment.",
    type: "watercolour",
  },
  {
    title: "Акрил",
    titleEn: "Acrylic",
    description:
      "Акриловые картины обычно относятся к искусству, созданному с использованием акриловой краски. Акриловая краска — это быстросохнущая краска, которая растворяется в воде во влажном состоянии, но становится водостойкой при высыхании.",
    descriptionEn:
      "Acrylic pictures typically refer to art created using acrylic paint. Acrylic paint is a fast-drying paint that is water-soluble when wet but becomes water-resistant when it dries.",
    type: "acrylic",
  },
  {
    title: "Phygital",
    titleEn: "Phygital",
    description:
      "Все цифровые работы состоят из множества акварелей, написанных Надеждой, объединенных и преобразованных в цифровой формат, тем самым усиливая эффект многомерности, бесконечности и трансформации.",
    descriptionEn:
      "All digital works consist of many watercolors painted by Nadia, combined and converted into a digital format, thereby enhancing the effect of multidimensionality, infinity and transformation.",
    type: "phygital",
  },
];
